### ISSUE TITLE
StreamTableUnoptimized sample

### ISSUE THREAD

**Issue by pravic** [DKorablin/PEReader#1]
Hi,

I've found your comment [here](https://github.com/DKorablin/PEReader/blob/master/PEReader/CorDirectory/MetaData.cs#L150).

Here is a sample for you: 
[unoptimized.zip](https://github.com/DKorablin/PEReader/files/721192/unoptimized.zip)

**Comment by DKorablin** [comment]
Thanks! I'll check it...

But be careful this files can contain harmful code:
https://www.virustotal.com/en/file/c2fc1e2c7af3766b59abd33da6e6438a22bbde445c6b07465efd1ff93cd53f0e/analysis/1485500712/

**Comment by pravic** [comment]
Hi. Was it useful?

**Comment by DKorablin** [comment]
Hi. Yes, thanks.
I could find error in stringHeap read by pointer.

That is strange that in the Param table (0x08) Name column points to invalid address...

File: unoptimized.dll
Address: 0x0001ea12
Size: 0x000005b8
String heap size: 0x0001a6fc
Data: [00,00,01,00,**FF,FF,FF,7F**,...]

By now Ive added one buffer check before try to read from string heap:
StringHeap.cs -> GetDataByPointer:

> if(pointer > base.Header.Size)
> 	throw new InvalidOperationException(String.Format("Pointer: {0:X} overflowed header. Size: {1:n0}", pointer, base.Header.Size));

And I have fond error in managed resources header. Valid magic is: 0xbeefcace but in the file: 0xd1a84c82 (I dont have time to check it right now...)
