### ISSUE TITLE
Project not buildable : missing sources - Symbolic Links

### ISSUE THREAD

**Issue by SoLaRGit** [DKorablin/PEReader#2]
1. Project files are trying to link to files that actual location is below solution folder.
Project Tree : PEReader10 + CorDirectory + Interface + IBaseRow.cs
Files can be restored manually by first removing them from project tree and re-adding correct ones.

2. Content of CS files literally contains the text as path to Symbolic Links.
check PEReader10 + ImageLoader + IImageLoader.cs file content for example:
"C:/Visual Studio Projects/C#/Shared.Classes/AlphaOmega.Debug/FileReader/ImageLoader/IImageLoader.cs"
Without original code this project is non build able (you can't check this on your OWN PC/TEAM PC's, since you have this files in above mentioned paths and VS "might" pull out correct paths - which I am not even sure VS will. Maybe you have some add-on that will, but ppl without this add-on won't).
Since you wanted to share between different projects apparently. Why this content is not external (SVN term) or different project and referenced as such, why Symbolic Links? 
I can imagine nightmare you have when you change interface or some code in this classes, you must recheck all other projects to see will they work. And separately commit to SVN for save keeping.

**Comment by DKorablin** [comment]
Thanks for the hint I'll fix it with hard links.

**Comment by taktopiyush** [comment]
Hi Korablin,
Excellent work done.
I am still unable to build the project due to these hardlinks and points to the location where no code can be found.
Could you please let us know if this link issues is fixed?

"C:/Visual Studio Projects/C#/Shared.Classes/AlphaOmega.Debug/FileReader/ImageData/IBaseRow.cs" this location is valid for anyone who wishes to checkout and test this code.

--
Thanks.
Steve

**Comment by DKorablin** [comment]
Missing items added:
https://github.com/DKorablin/PEReader/tree/master/PEReader/ImageLoader
https://github.com/DKorablin/PEReader/tree/master/PEReader/CorDirectory/Interface
